apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gcsfuse-sc # dummy storage class
  # claimRef:
  #   name: customer-namespace
    # namespace: customer-data
  mountOptions:
    - debug_fuse
    - implicit-dirs #avoid if list cache enabled and doing metadata prefetch
    - max-conns-per-host=0
    - metadata-cache:ttl-secs:-1
    - metadata-cache:stat-cache-max-size-mb:-1
    - metadata-cache:type-cache-max-size-mb:-1
    - file-system:kernel-list-cache-ttl-secs:-1
    - file-cache:max-size-mb:-1
    - file-cache:cache-file-for-range-read:true
    - file-cache:enable-parallel-downloads:true
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: rick-llama-factory # unique bucket name
    volumeAttributes:
      skipCSIBucketAccessCheck: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-data
  namespace: training-job
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
     storage: 1000Gi
  volumeName: gcs-pv
  storageClassName: gcsfuse-sc # dummy storage class                 

